import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.scss";

const Home = () => {
     return (
          <div className={styles.container}>
               <Head>
                    <title>Home</title>
                    <meta name="description" content="Generated by create next app"/>
                    <link rel="icon" href="/Avatar.png" />
               </Head>
               <main className={styles.main}>
               </main>
          </div>
     );
};

export default Home;
